### ISSUE TITLE
Docs: usage of `activate` in the initial example

### ISSUE THREAD

**Issue by akrzemi1** [Lastique/scope#1]
The initial example in the docs uses:

```c++
it->activate(arg);
```

This is a bit confusing, given that guards have a member function `set_active`, one starts to wonder if `it` points to a guard. Any other name, like `start`, would be better.

Anyway, is this a real life example? Wouldn't you rather create an automatic object, activate (or start) it there, and then move into the set? This way, you do not need a guard.

**Comment by Lastique** [comment]
`it` is not pointing to a scope guard but a user's object. Here, `activate` is not supposed to mean something specific, it's just a placeholder to show that you do something on the inserted object that may potentially throw. I can rename the method, no problem.

> Anyway, is this a real life example?

Yes, more or less. I've had code similar to this, where the object needed to be added to some sort of collection before it could be "activated", because it relied on the fact that it is present in the collection at that point.

**Comment by Lastique** [comment]
Done. Thanks.
